export const USER_PROFILE = "app/UserProfile/USER_PROFILE";
export const USER_PROFILE_SUCCESS = "app/UserProfile/USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE =  "app/UserProfile/USER_PROFILE_SUCCESS";

export const GET_SHIPPING_DETAILS = "APP/USER_PROFILE/GET_SHIPPING_DETAILS";
export const GET_SHIPPING_DETAILS_SUCCESS = "APP/USER_PROFILE/GET_SHIPPING_DETAILS_SUCCESS";
export const GET_SHIPPING_DETAILS_FAILURE = "APP/USER_PROFILE/GET_SHIPPING_DETAILS_FAILURE";
